# syntax=docker/dockerfile:1

# ---------- Development Layer ----------
FROM node:24-slim AS development

ENV NODE_ENV="development"
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
